[package]
name = "qrts-search"
version = "0.1.0"
authors = ["kevinlmadison <coolklm121@gmail.com>"]

[dependencies]
walkdir = "2"

[dependencies.clap]
version = "2"
features = ["yaml", "color", "suggestions"]
