[package]
name = "qrts-search"
version = "0.1.0"
authors = ["kevinlmadison <coolklm121@gmail.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
walkdir = "2"
appdirs = "0.2.0"
regex = "1"

[dependencies.clap]
version = "2"
features = ["yaml", "color", "suggestions"]
